### ISSUE TITLE
Сайт

### ISSUE THREAD

**Issue by DewLo** [d3dipa/XGPB#1]
@FoxSenpaiii, загрузи сюда сайт до 28.04.2021 до 9:00!

**Comment by FoxSenpaiii** [comment]
ТЫ ОФИГЕЛ ????? ЛАДНО ЩАС БУДЕТ

**Comment by FoxSenpaiii** [comment]
[top secret.zip](https://github.com/d3dipa/XGPB/files/6383872/top.secret.zip)
НА ЖРИ!

**Comment by FoxSenpaiii** [comment]
Ща запушу
